- samples/DotNet/Microsoft.Azure.ServiceBus/SendSample/readme.md
> Fix example in readme file

- samples/DotNet/Microsoft.ServiceBus.Messaging/AtomicTransactions/readme.md
Fixed some formatting issues in sample.
> Fixed formatting of AtomicTransactions sample

- samples/DotNet/Microsoft.Azure.ServiceBus/ReceiveSample/Program.cs
- samples/DotNet/Microsoft.Azure.ServiceBus/ReceiveSample/ReceiveSample.csproj
- samples/DotNet/Microsoft.Azure.ServiceBus/ReceiveSample/readme.md
- samples/DotNet/Microsoft.Azure.ServiceBus/SendSample/SendSample.csproj
Addresses https://github.com/Azure/azure-service-bus-dotnet/issues/229
> Update to 0.0.7-preview and demonstration of the error callback

- samples/Java/Samples.iml
- samples/Java/azure-servicebus-samples.iml
- samples/Java/pom.xml
- samples/Java/src/com/microsoft/azure/servicebus/samples/JmsInterop.java
- samples/Java/src/log4j.properties
Adding sample for sending message from qpid jms and receive from service bus java client
> Adding jms sample

- samples/DotNet/Microsoft.Azure.ServiceBus/TopicSubscriptionWithRuleOperationsSample/Program.cs
- samples/Java/azure-servicebus-samples.iml
- samples/Java/pom.xml
- samples/Java/src/com/microsoft/azure/servicebus/samples/TopicSubscriptionWithRuleOperations.java
Sample for usage of rules in java client library
> Sample for usage of rules in java client library

- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/SBGeoDR2/SBGeoDR2/App.config
- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/SBGeoDR2/SBGeoDR2/Program.cs
- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/SBGeoDR2/SBGeoDR2/SBGeoDR2.csproj
- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/TestGeoDR/ConsoleApp1/App.config
- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/TestGeoDR/ConsoleApp1/Program.cs
- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/TestGeoDR/ConsoleApp1/TestGeoDR.csproj
Addressing comments made in the review of PR #93 
- Make code async top to bottom
- Refactoring
- Cleanups
> Suggested changes to from PR #93 review

- samples/Java/azure-servicebus/MessageReceiverQuickstart/readme.md
- samples/Java/azure-servicebus/QueueClientQuickstart/readme.md
- samples/Java/qpid-jms-client/JmsQueueQuickstart/readme.md
Readme text fixes in the Java samples
> readme corrections

- samples/Java/azure-servicebus/MessageReceiverQuickstart/readme.md
- samples/Java/azure-servicebus/QueueClientQuickstart/readme.md
- samples/Java/qpid-jms-client/JmsQueueQuickstart/readme.md
> Pull packages to master

- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/SBGeoDR2/SBGeoDR2/packages.config
- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/TestGeoDR/ConsoleApp1/packages.config
> Geodr - move packages over

- samples/DotNet/Microsoft.ServiceBus.Messaging/README.md
> Type in Readme.md

- samples/DotNet/Microsoft.Azure.ServiceBus/BasicSendReceiveUsingQueueClient/BasicSendReceiveUsingQueueClient.csproj
- samples/DotNet/Microsoft.Azure.ServiceBus/BasicSendReceiveUsingTopicSubscriptionClient/BasicSendReceiveUsingTopicSubscriptionClient.csproj
- samples/DotNet/Microsoft.Azure.ServiceBus/BasicSessionSendReceiveUsingQueueClient/BasicSessionSendReceiveUsingQueueClient.csproj
- samples/DotNet/Microsoft.Azure.ServiceBus/SendReceiveUsingMessageSenderReceiver/SendReceiveUsingMessageSenderReceiver.csproj
- samples/DotNet/Microsoft.Azure.ServiceBus/SessionSendReceiveUsingSessionClient/SessionSendReceiveUsingSessionClient.csproj
- samples/DotNet/Microsoft.Azure.ServiceBus/TopicSubscriptionWithRuleOperationsSample/TopicSubscriptionWithRuleOperationsSample.csproj
> Updating samples to use 2.0 package

- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/BasicSendReceiveUsingQueueClient/BasicSendReceiveUsingQueueClient.csproj
- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/BasicSendReceiveUsingQueueClient/Program.cs
- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/BasicSendReceiveUsingQueueClient/readme.md
- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/BasicSendReceiveUsingTopicSubscriptionClient/BasicSendReceiveUsingTopicSubscriptionClient.csproj
- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/BasicSendReceiveUsingTopicSubscriptionClient/Program.cs
- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/BasicSendReceiveUsingTopicSubscriptionClient/readme.md
- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/BasicSessionSendReceiveUsingQueueClient/BasicSessionSendReceiveUsingQueueClient.csproj
- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/BasicSessionSendReceiveUsingQueueClient/Program.cs
- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/BasicSessionSendReceiveUsingQueueClient/readme.md
- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/Microsoft.Azure.ServiceBus.Samples.sln
- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/SendReceiveUsingMessageSenderReceiver/Program.cs
- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/SendReceiveUsingMessageSenderReceiver/SendReceiveUsingMessageSenderReceiver.csproj
- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/SendReceiveUsingMessageSenderReceiver/readme.md
- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/SessionSendReceiveUsingSessionClient/Program.cs
- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/SessionSendReceiveUsingSessionClient/SessionSendReceiveUsingSessionClient.csproj
- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/SessionSendReceiveUsingSessionClient/readme.md
- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/TopicSubscriptionWithRuleOperationsSample/Program.cs
- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/TopicSubscriptionWithRuleOperationsSample/TopicSubscriptionWithRuleOperationsSample.csproj
- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/TopicSubscriptionWithRuleOperationsSample/readme.md
> Adding back the get started samples

- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/README.md
- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/SBGeoDR2/SBGeoDR2/App.config
- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/SBGeoDR2/SBGeoDR2/AssemblyInfo.cs
- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/SBGeoDR2/SBGeoDR2/Properties/AssemblyInfo.cs
- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/SBGeoDR2/SBGeoDR2/SBGeoDR2.csproj
- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/SBGeoDR2/SBGeoDR2/SBGeoDR2.sln
- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/SBGeoDR2/SBGeoDR2/packages.config
- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/SBGeoDR2/SBGeoDR_existing_namespace_name/App.config
- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/SBGeoDR2/SBGeoDR_existing_namespace_name/AssemblyInfo.cs
- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/SBGeoDR2/SBGeoDR_existing_namespace_name/Program.cs
- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/SBGeoDR2/SBGeoDR_existing_namespace_name/Properties/AssemblyInfo.cs
- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/SBGeoDR2/SBGeoDR_existing_namespace_name/SBGeoDR2_existing_namespace_name.csproj
- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/SBGeoDR2/SBGeoDR_existing_namespace_name/SBGeoDR2_existing_namespace_name.sln
- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/SBGeoDR2/SBGeoDR_existing_namespace_name/packages.config
- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/TestGeoDR/ConsoleApp1/App.config
- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/TestGeoDR/ConsoleApp1/AssemblyInfo.cs
- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/TestGeoDR/ConsoleApp1/Program.cs
- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/TestGeoDR/ConsoleApp1/Properties/AssemblyInfo.cs
- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/TestGeoDR/ConsoleApp1/TestGeoDR.sln
- samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/TestGeoDR/ConsoleApp1/packages.config
> Geodrsample

- samples/DotNet/Microsoft.ServiceBus.Messaging/ManagedServiceIdentity/ManagedServiceIdentityWebApp/default.aspx.cs
- samples/DotNet/Microsoft.ServiceBus.Messaging/ManagedServiceIdentity/README.md
- samples/DotNet/Microsoft.ServiceBus.Messaging/RoleBasedAccessControl/README.md
> Adding Readmes

- samples/DotNet/Microsoft.ServiceBus.Messaging/ManagedServiceIdentity/README.md
- samples/DotNet/Microsoft.ServiceBus.Messaging/RoleBasedAccessControl/README.md
> Fixing links back to the docs

- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/BasicSendReceiveUsingTopicSubscriptionClient/Program.cs
- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/BasicSendReceiveUsingTopicSubscriptionClient/readme.md
- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/TopicSubscriptionWithRuleOperationsSample/Program.cs
Address https://github.com/Azure/azure-service-bus-dotnet/issues/348#issuecomment-359875424
- Ensure subscriptions that rely on `$Default` rule have it
- Add a note to the doco
> Subscription sample clarification

- samples/DotNet/Microsoft.ServiceBus.Messaging/ManagedServiceIdentity/ManagedServiceIdentityWebApp/default.aspx.cs
The sample has a workaround (TODO comment) which will be used by anyone using this code w/o a tracking issue to know when this workaround can be safely remove.
Please open an issue and provide add a tracking issue link.
> TODO should contain a tracking issue

- samples/Java/readme.md
> Fix java readme

- samples/Java/azure-servicebus/README.md
- samples/Java/azure-servicebus/ScheduledMessages/src/main/java/com/microsoft/azure/servicebus/samples/scheduledmessages/ScheduledMessages.java
Also replacing .net standard readme file with java readme file inside java samples directory.
> Changing scheduled messages sample enqueue time delay to 2 minutes.

- samples/DotNet/Microsoft.Azure.ServiceBus/TopicsGettingStarted/README.md
Simple typo in the readme addressed
> fix typo of word 'topics' in readme.md

- samples/Java/quickstarts-and-tutorials/quickstart-java/pom.xml
> Removing comments

- samples/DotNet/Microsoft.ServiceBus.Messaging/README.md
> Fixing readme typos

- samples/DotNet/Microsoft.ServiceBus.Messaging/ManagedServiceIdentity/ManagedServiceIdentityWebApp/default.aspx.cs
- samples/DotNet/Microsoft.ServiceBus.Messaging/RoleBasedAccessControl/Program.cs
> UpdatingMSI and RBAC sample, smaller fixes

- samples/Java/quickstarts-and-tutorials/quickstart-java/pom.xml
- samples/Java/quickstarts-and-tutorials/quickstart-jms/pom.xml
> Adding dependency

- samples/readme.md
> updating samples readme

- samples/Management/Metrics/AccessServiceBusMetricsViaCode/Program.cs
> Remove creds

- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/BasicSendReceiveUsingQueueClient/readme.md
Fixed line 156, where method was called SendMessagesToQueue instead of SendMessagesAsync
> fixed typo - should have been SendMessagesAsync

- .gitmodules
> Adding submodule branch

- samples/Management/Metrics/AccessServiceBusMetricsViaCode/AccessServiceBusMetricsViaCode.csproj
- samples/Management/Metrics/AccessServiceBusMetricsViaCode/Program.cs
> Metrics Sample - Use c# 7.1 to run console app async & Re-use aggregation & metricName

- samples/DotNet/GettingStarted/BasicSendReceiveTutorialwithFilters/BasicSendReceiveTutorialWithFilters/Extensions.cs
- samples/DotNet/GettingStarted/BasicSendReceiveTutorialwithFilters/BasicSendReceiveTutorialWithFilters/Program.cs
- samples/DotNet/GettingStarted/BasicSendReceiveTutorialwithFilters/BasicSendReceiveTutorialWithFilters/SendReceive.cs
The code has a flow - the loop might leave prematurely before all messages are recieved.
A better approach could be to count the received messages and stop receiving code once all messages where retrieved.
@ChristianWolf42 please review
> Batched receive

- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/BasicSendReceiveUsingQueueClient/BasicSendReceiveUsingQueueClient.csproj
- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/BasicSendReceiveUsingTopicSubscriptionClient/BasicSendReceiveUsingTopicSubscriptionClient.csproj
- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/BasicSessionSendReceiveUsingQueueClient/BasicSessionSendReceiveUsingQueueClient.csproj
- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/SendReceiveUsingMessageSenderReceiver/SendReceiveUsingMessageSenderReceiver.csproj
- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/SessionSendReceiveUsingSessionClient/SessionSendReceiveUsingSessionClient.csproj
- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/TopicSubscriptionWithRuleOperationsSample/TopicSubscriptionWithRuleOperationsSample.csproj
fixes https://github.com/Azure/azure-service-bus-dotnet/issues/567
> Update ASB  version to 3.*

- samples/DotNet/Microsoft.Azure.ServiceBus/Sessions/Program.cs
For Session Dotnet Samples, fix ignored ExceptionReceivedContext.EntityPath in LogMessageHandlerException.
> Fix Ignored  ExceptionReceivedContext.EntityPath in DotNet Session Sample

- samples/Java/azure-servicebus/QueuesWithProxy/src/main/java/com/microsoft/azure/servicebus/samples/queueswithproxy/QueuesWithProxy.java
Fix error in previous PR which was merged before I could respond to it
- [ x ] **I have read the [contribution guidelines](./CONTRIBUTING.md).**
- [ x ] Title of the pull request is clear and informative.
- [ x ] If applicable, the code is properly documented.
- [ x ] The code builds without any errors.
> Remove TODO & uncomment line that needed proxy support

- samples/Java/readme.md
- [ok] **I have read the [contribution guidelines](./CONTRIBUTING.md).**
- [ok] Title of the pull request is clear and informative.
- [ok] If applicable, the code is properly documented.
- [ok] The code builds without any errors.
> Removed an extra 's' at the end of queue

- samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/SendReceiveUsingMessageSenderReceiver/readme.md
Small typos in documentation of `SendReceiveUsingMessageSenderReceiver` sample
Also a missing variable.
All this information was available in the code itself, but not the documentation.
> Typos ans missing variable in documentation of SendReceiveUsingMessageSenderReceiver sample

- samples/DotNet/Microsoft.ServiceBus.Messaging/RoleBasedAccessControl/Program.cs
Sample for MSI/RBAC
TODO
- Update library reference for latest SDK
> Update sample for MSI/RBAC

- samples/DotNet/Microsoft.ServiceBus.Messaging/RoleBasedAccessControl/Program.cs
The default audience in the TokenProvider has to be updated. This change executes the change in the sample to enable the sample to work.
> updating audience override in MSI/RBAC sample

- README.md
Update the client link to point to the new repository URL.
> Update client repository link

- samples/DotNet/Microsoft.ServiceBus.Messaging/RoleBasedAccessControl/Program.cs
> minor tweak

- samples/DotNet/Microsoft.Azure.ServiceBus/RoleBasedAccessControl/App.config
- samples/DotNet/Microsoft.Azure.ServiceBus/RoleBasedAccessControl/Program.cs
- samples/DotNet/Microsoft.Azure.ServiceBus/RoleBasedAccessControl/README.md
- samples/DotNet/Microsoft.Azure.ServiceBus/RoleBasedAccessControl/RoleBasedAccessControl.csproj
- samples/DotNet/Microsoft.Azure.ServiceBus/RoleBasedAccessControl/RoleBasedAccessControl.sln
> Enhance Track1 RoleBasedAccessControl sample

- samples/DotNet/Microsoft.Azure.ServiceBus/RoleBasedAccessControl/App.config
- samples/DotNet/Microsoft.Azure.ServiceBus/RoleBasedAccessControl/Program.cs
- samples/DotNet/Microsoft.Azure.ServiceBus/RoleBasedAccessControl/README.md
- samples/DotNet/Microsoft.Azure.ServiceBus/RoleBasedAccessControl/RoleBasedAccessControl.csproj
- samples/DotNet/Microsoft.Azure.ServiceBus/RoleBasedAccessControl/RoleBasedAccessControl.sln
….Messaging directory.
This fixes #338.
> New sample RoleBasedAccessControl using Track 1 SDK

- samples/DotNet/Microsoft.ServiceBus.Messaging/RoleBasedAccessControl/Program.cs
- samples/DotNet/Microsoft.ServiceBus.Messaging/RoleBasedAccessControl/RoleBasedAccessControl.csproj
> Changed dependencies and code to make the WindowsAzure.ServiceBus RoleBasedAccessControl sample build and work

- samples/DotNet/Azure.Messaging.ServiceBus/BasicSendReceiveTutorialwithFilters/BasicSendReceiveTutorialWithFilters/BasicSendReceiveTutorialWithFilters.csproj
- samples/DotNet/Azure.Messaging.ServiceBus/BasicSendReceiveTutorialwithFilters/BasicSendReceiveTutorialWithFilters/Extensions.cs
- samples/DotNet/Azure.Messaging.ServiceBus/BasicSendReceiveTutorialwithFilters/BasicSendReceiveTutorialWithFilters/SendReceive.cs
- samples/DotNet/Azure.Messaging.ServiceBus/MessageSender/MessageSender.csproj
- samples/DotNet/Azure.Messaging.ServiceBus/ServiceBusEventGridIntegrationV2/FunctionApp1/FunctionApp1.csproj
Upgraded projects to use the latest Preview. I had to made one minor code change.
> upgrading to use latest packages

- samples/DotNet/Azure.Messaging.ServiceBus/TopicSubscriptionFilters/CreateTopicAndSubscriptions/CreateTopicsAndSubscriptions.csproj
- samples/DotNet/Azure.Messaging.ServiceBus/TopicSubscriptionFilters/CreateTopicAndSubscriptions/Program.cs
- samples/DotNet/Azure.Messaging.ServiceBus/TopicSubscriptionFilters/Readme.md
- samples/DotNet/Azure.Messaging.ServiceBus/TopicSubscriptionFilters/SendAndReceiveMessages/Order.cs
- samples/DotNet/Azure.Messaging.ServiceBus/TopicSubscriptionFilters/SendAndReceiveMessages/Program.cs
- samples/DotNet/Azure.Messaging.ServiceBus/TopicSubscriptionFilters/SendAndReceiveMessages/SendAndReceiveMessages.csproj
- samples/DotNet/Azure.Messaging.ServiceBus/TopicSubscriptionFilters/TopicSubscriptionFilters.sln
We have a TopicFilters sample for the Track 1 package Microsoft.Azure.ServiceBus, but we don't have a similar one for Track 2 SDK. I have created this samples that creates the following entities and then sends and receives messages to test the filters on subscription.
1. A topic named `TopicFilterSampleTopic`.
2. Subscriptions to the above topic with the following settings. 
| Subscription name |  Filter type |  Filter expression | Action | 
| --------- | ----------- | ------------------ | ------ | 
| AllOrders | True Rule filter | `1=1` | |
| ColorBlueSize10Orders | SQL filter | `color = 'blue' AND quantity = 10` | | 
| ColorRed | SQL filter | `color = 'red'` | `SET quantity = quantity / 2;REMOVE priority; SET sys.CorrelationId = 'low'`| 
| ColorRed | Correlation filter | `"label": …
> Azure.Messaging.ServiceBus sample for subscription filters

- samples/Java/azure-servicebus/ManagingTopicRules/src/main/java/com/microsoft/azure/servicebus/samples/managingtopicrules/ManagingTopicRules.java
- samples/Java/azure-servicebus/SasAuthorization/src/main/java/com/microsoft/azure/servicebus/samples/sasauthorization/SasAuthorization.java
Hi
I have removed some unused imports from the code
all the best
matteo baccan
> Removed unused imports

- samples/DotNet/Microsoft.ServiceBus.Messaging/PerformanceCounters/PerformanceCounterSetup/ServiceConfiguration.Cloud.cscfg
Addressing security vulnerability reported by removing old storage connection string
- [ x ] **I have read the [contribution guidelines](./CONTRIBUTING.md).**
- [ x ] Title of the pull request is clear and informative.
- [ x ] The code builds without any errors.
> [dotNet] Removing Exposed Azure Storage and Service Bus Connection Strings
